use_frameworks!

platform :ios, '10.0'

target 'AelfPortkey_Example' do
  pod 'AelfPortkey', :path => '../'

  target 'AelfPortkey_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
